---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tce/public_html/yeni/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R index.php $DEPLOYPATH
    - /bin/cp -R router.php $DEPLOYPATH
    - /bin/cp -R .htaccess $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R pages $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R tools $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/storage
    - /bin/chmod 755 $DEPLOYPATH/storage
