---
deployment:
  tasks:
    - /bin/mkdir -p /home/tce/public_html/yeni
    - /bin/mkdir -p /home/tce/public_html/yeni/storage
    - /bin/cp -f index.php /home/tce/public_html/yeni/
    - /bin/cp -f router.php /home/tce/public_html/yeni/
    - /bin/cp -f .htaccess /home/tce/public_html/yeni/
    - /bin/cp -f README.md /home/tce/public_html/yeni/
    - /bin/cp -Rf config /home/tce/public_html/yeni/
    - /bin/cp -Rf includes /home/tce/public_html/yeni/
    - /bin/cp -Rf pages /home/tce/public_html/yeni/
    - /bin/cp -Rf assets /home/tce/public_html/yeni/
    - /bin/cp -Rf tools /home/tce/public_html/yeni/
    - /bin/chmod 755 /home/tce/public_html/yeni/storage
